version: "3.8"

services:

  sensorial-raspberry:
    image: utnsensorial/sensorial-raspberry:latest
    container_name: sensorial-raspberry
    restart: on-failure:3
    privileged: true
    environment:
      - LOG_MAX_KB=1000
      - LOG_BACKUP_COUNT=2
      - LOG_LEVEL=INFO
      - SEND_BACKEND_SECONDS=60
      - SEND_BACKEND_MAX_METRICS=50
      - SEND_BACKEND_TRIES=3
      - SEND_BACKEND_URL=https://sensorial-back.herokuapp.com/api/v1/mediciones
    volumes: 
      - sensorial-raspberry:/home/utn/.sensorial:rw
    ports:
      - 80:80
    networks: 
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: false
  
volumes:
  sensorial-raspberry:
    name: sensorial-raspberry
    external: false
